/**
 * Architecture Report Exporter
 *
 * Generates a comprehensive Markdown design document from the architecture graph.
 * Includes: overview, component inventory, data flow matrix, validation issues,
 * AI recommendations, and infrastructure notes.
 */

import type { SerializedNode, SerializedEdge, ValidationResult } from "@system-synthesis/shared";
import { validateArchitecture } from "../validation.js";

// ── Report Generator ───────────────────────────────────────────────

export function generateReport(
  nodes: SerializedNode[],
  edges: SerializedEdge[],
  boardName: string = "Untitled Architecture"
): string {
  const validation = validateArchitecture(nodes, edges);
  const now = new Date().toISOString().split("T")[0];

  const sections: string[] = [];

  // ── Title & Overview ──
  sections.push(`# ${boardName} — Architecture Design Document`);
  sections.push(``);
  sections.push(`> Auto-generated by **System Synthesis** on ${now}`);
  sections.push(``);
  sections.push(`---`);
  sections.push(``);
  sections.push(`## 1. Overview`);
  sections.push(``);
  sections.push(`| Metric | Value |`);
  sections.push(`|--------|-------|`);
  sections.push(`| Total Components | ${nodes.length} |`);
  sections.push(`| Total Connections | ${edges.length} |`);
  sections.push(`| Validation Issues | ${validation.issues.length} (${validation.stats.critical} critical, ${validation.stats.warning} warning, ${validation.stats.info} info) |`);
  sections.push(``);

  // Tier distribution
  const tierCounts: Record<string, number> = {};
  nodes.forEach((n) => {
    const tier = (n.data.tier as string) || "unassigned";
    tierCounts[tier] = (tierCounts[tier] || 0) + 1;
  });
  sections.push(`### Tier Distribution`);
  sections.push(``);
  sections.push(`| Tier | Count |`);
  sections.push(`|------|-------|`);
  for (const [tier, count] of Object.entries(tierCounts).sort((a, b) => b[1] - a[1])) {
    sections.push(`| ${tier} | ${count} |`);
  }
  sections.push(``);

  // ── Component Inventory ──
  sections.push(`---`);
  sections.push(``);
  sections.push(`## 2. Component Inventory`);
  sections.push(``);
  sections.push(`| # | Component | Type | Tier | Zone | Technology | Instances | SLA |`);
  sections.push(`|---|-----------|------|------|------|------------|-----------|-----|`);

  const sortedNodes = [...nodes].sort((a, b) => {
    const tierOrder = ["frontend", "infrastructure", "backend", "data", "external"];
    const ai = tierOrder.indexOf((a.data.tier as string) || "");
    const bi = tierOrder.indexOf((b.data.tier as string) || "");
    return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
  });

  sortedNodes.forEach((n, i) => {
    sections.push(
      `| ${i + 1} | **${n.data.label}**${n.data.subtitle ? ` <br/>_${n.data.subtitle}_` : ""} | ${n.data.nodeType} | ${(n.data.tier as string) || "—"} | ${(n.data.zone as string) || "—"} | ${(n.data.tech as string) || "—"} | ${n.data.instances || 1} | ${(n.data.sla as string) || "—"} |`
    );
  });
  sections.push(``);

  // ── Data Flow Matrix ──
  sections.push(`---`);
  sections.push(``);
  sections.push(`## 3. Data Flow Matrix`);
  sections.push(``);

  if (edges.length === 0) {
    sections.push(`_No connections defined._`);
  } else {
    sections.push(`| Source | → | Target | Label | Protocol |`);
    sections.push(`|--------|---|--------|-------|----------|`);

    const nodeMap = new Map(nodes.map((n) => [n.id, n.data.label]));
    edges.forEach((e) => {
      const source = nodeMap.get(e.source) || e.source;
      const target = nodeMap.get(e.target) || e.target;
      const label = e.data?.label || "—";
      const protocol = e.data?.protocol || "—";
      sections.push(`| ${source} | → | ${target} | ${label} | ${protocol} |`);
    });
  }
  sections.push(``);

  // ── Zone Map ──
  const zones = new Map<string, string[]>();
  nodes.forEach((n) => {
    const zone = (n.data.zone as string) || "unassigned";
    const list = zones.get(zone) || [];
    list.push(n.data.label);
    zones.set(zone, list);
  });

  sections.push(`---`);
  sections.push(``);
  sections.push(`## 4. Network Zones`);
  sections.push(``);

  const zoneOrder = ["public", "dmz", "private", "restricted", "unassigned"];
  const zoneEmojis: Record<string, string> = {
    public: "🌐",
    dmz: "🛡️",
    private: "🔒",
    restricted: "⛔",
    unassigned: "❓",
  };

  for (const zone of zoneOrder) {
    const members = zones.get(zone);
    if (!members) continue;
    sections.push(`### ${zoneEmojis[zone] || "•"} ${zone.charAt(0).toUpperCase() + zone.slice(1)} Zone`);
    sections.push(``);
    members.forEach((m) => sections.push(`- ${m}`));
    sections.push(``);
  }

  // ── Validation Report ──
  sections.push(`---`);
  sections.push(``);
  sections.push(`## 5. Validation Report`);
  sections.push(``);

  if (validation.issues.length === 0) {
    sections.push(`✅ **All validation checks passed.** No issues detected.`);
  } else {
    const sevEmoji: Record<string, string> = {
      critical: "🔴",
      warning: "🟡",
      info: "🔵",
    };

    sections.push(`| # | Severity | Issue | Affected Components |`);
    sections.push(`|---|----------|-------|---------------------|`);

    validation.issues.forEach((issue, i) => {
      const affectedLabels = issue.nodeIds
        .map((id) => {
          const n = nodes.find((n) => n.id === id);
          return n ? n.data.label : id;
        })
        .join(", ");
      sections.push(
        `| ${i + 1} | ${sevEmoji[issue.severity] || "•"} ${issue.severity} | **${issue.title}** — ${issue.description} | ${affectedLabels || "—"} |`
      );
    });
  }
  sections.push(``);

  // ── Technology Stack Summary ──
  sections.push(`---`);
  sections.push(``);
  sections.push(`## 6. Technology Stack`);
  sections.push(``);

  const techSet = new Set<string>();
  nodes.forEach((n) => {
    if (n.data.tech) techSet.add(n.data.tech as string);
  });

  if (techSet.size === 0) {
    sections.push(`_No technologies specified. Assign technologies to components in the Inspector._`);
  } else {
    sections.push(`| Technology | Used By |`);
    sections.push(`|------------|---------|`);

    const techUsers = new Map<string, string[]>();
    nodes.forEach((n) => {
      if (n.data.tech) {
        const tech = n.data.tech as string;
        const users = techUsers.get(tech) || [];
        users.push(n.data.label);
        techUsers.set(tech, users);
      }
    });

    for (const [tech, users] of [...techUsers.entries()].sort()) {
      sections.push(`| ${tech} | ${users.join(", ")} |`);
    }
  }
  sections.push(``);

  // ── Infrastructure Notes ──
  sections.push(`---`);
  sections.push(``);
  sections.push(`## 7. Infrastructure Notes`);
  sections.push(``);

  // SLA requirements
  const slaNodes = nodes.filter((n) => n.data.sla);
  if (slaNodes.length > 0) {
    sections.push(`### SLA Requirements`);
    sections.push(``);
    slaNodes.forEach((n) => {
      sections.push(`- **${n.data.label}**: ${n.data.sla} (${n.data.instances || 1} instance${(n.data.instances || 1) > 1 ? "s" : ""})`);
    });
    sections.push(``);
  }

  // Multi-instance components
  const multiInstance = nodes.filter((n) => (n.data.instances || 1) > 1);
  if (multiInstance.length > 0) {
    sections.push(`### Horizontally Scaled Components`);
    sections.push(``);
    multiInstance.forEach((n) => {
      sections.push(`- **${n.data.label}**: ${n.data.instances} instances`);
    });
    sections.push(``);
  }

  // Region distribution
  const regions = new Map<string, string[]>();
  nodes.forEach((n) => {
    if (n.data.region) {
      const region = n.data.region as string;
      const list = regions.get(region) || [];
      list.push(n.data.label);
      regions.set(region, list);
    }
  });
  if (regions.size > 0) {
    sections.push(`### Region Distribution`);
    sections.push(``);
    for (const [region, members] of regions) {
      sections.push(`- **${region}**: ${members.join(", ")}`);
    }
    sections.push(``);
  }

  // ── Footer ──
  sections.push(`---`);
  sections.push(``);
  sections.push(`_This document was auto-generated by System Synthesis. For the latest version, re-export from the canvas._`);
  sections.push(``);

  return sections.join("\n");
}
