/**
 * Docker Compose Export — Unit Tests
 *
 * Validates that the Docker Compose generator produces
 * correct YAML structure for various architectures.
 */

import { describe, it, expect } from "vitest";
import { generateDockerCompose } from "../../services/export/docker-compose.js";
import type { SerializedNode, SerializedEdge } from "@system-synthesis/shared";

// ── Helpers ──────────────────────────────────────────────────────────

function makeNode(
  id: string,
  nodeType: string,
  overrides: Record<string, unknown> = {}
): SerializedNode {
  return {
    id,
    type: "architectureNode",
    position: { x: 0, y: 0 },
    data: {
      label: id,
      nodeType,
      status: "active",
      metadata: { notes: "", links: [], codeSnippet: "", attachedFiles: [] },
      ...overrides,
    },
  } as SerializedNode;
}

function makeEdge(id: string, source: string, target: string): SerializedEdge {
  return { id, source, target, data: {} } as SerializedEdge;
}

// ── Tests ────────────────────────────────────────────────────────────

describe("generateDockerCompose", () => {
  it("returns a valid YAML string with header comments", () => {
    const output = generateDockerCompose(
      [makeNode("api", "service")],
      []
    );
    expect(output).toContain("version:");
    expect(output).toContain("services:");
    expect(output).toContain("Generated by System Synthesis");
  });

  it("generates correct service for a database node", () => {
    const output = generateDockerCompose(
      [makeNode("db", "database", { label: "Main DB" })],
      []
    );
    expect(output).toContain("postgres");
    expect(output).toContain("5432");
  });

  it("maps tech-specific images (Redis)", () => {
    const output = generateDockerCompose(
      [makeNode("cache", "cache", { label: "Session Cache", tech: "Redis" })],
      []
    );
    expect(output).toContain("redis:7-alpine");
    expect(output).toContain("6379");
  });

  it("maps tech-specific images (Kafka)", () => {
    const output = generateDockerCompose(
      [makeNode("mq", "queue", { label: "Event Bus", tech: "Kafka" })],
      []
    );
    expect(output).toContain("confluentinc/cp-kafka");
    expect(output).toContain("9092");
  });

  it("generates depends_on from edges", () => {
    const nodes = [
      makeNode("api", "service", { label: "API" }),
      makeNode("db", "database", { label: "Database" }),
    ];
    const edges = [makeEdge("e1", "api", "db")];
    const output = generateDockerCompose(nodes, edges);
    expect(output).toContain("depends_on:");
    expect(output).toContain("database");
  });

  it("generates named volumes for stateful services", () => {
    const output = generateDockerCompose(
      [makeNode("db", "database", { label: "Postgres", tech: "PostgreSQL" })],
      []
    );
    expect(output).toContain("volumes:");
    expect(output).toContain("pgdata");
    expect(output).toContain("driver: local");
  });

  it("skips client nodes (browsers are not Docker services)", () => {
    const output = generateDockerCompose(
      [
        makeNode("browser", "client", { label: "Web Browser" }),
        makeNode("api", "service", { label: "API" }),
      ],
      []
    );
    expect(output).not.toContain("web-browser:");
    expect(output).toContain("api:");
  });

  it("generates zone-based networks", () => {
    const output = generateDockerCompose(
      [makeNode("api", "service", { label: "API", zone: "private" })],
      []
    );
    expect(output).toContain("networks:");
    expect(output).toContain("private");
    expect(output).toContain("driver: bridge");
  });

  it("sets deploy replicas when instances > 1", () => {
    const output = generateDockerCompose(
      [makeNode("api", "service", { label: "API", instances: 3 })],
      []
    );
    expect(output).toContain("deploy:");
    expect(output).toContain("replicas: 3");
  });

  it("handles empty board gracefully", () => {
    const output = generateDockerCompose([], []);
    expect(output).toContain("services:");
    // No crash, valid YAML header
    expect(output).toContain("version:");
  });
});
